-- CreateEnum
CREATE TYPE "GooglePlayStatus" AS ENUM ('PRODUCTION', 'CLOSED_TESTING', 'INTERNAL_TESTING', 'OPEN_TESTING', 'PRODUCTION_REVIEW', 'NOT_CONFIGURED');

-- AlterTable
ALTER TABLE "App" ADD COLUMN "googlePlayStatus" "GooglePlayStatus" NOT NULL DEFAULT 'NOT_CONFIGURED';
ALTER TABLE "App" ADD COLUMN "testerTarget" INTEGER NOT NULL DEFAULT 12;
ALTER TABLE "App" ADD COLUMN "playConflictNote" TEXT;
